record_types:
  A:
    emad:
      - content: 192.168.1.1
        weight: 10
      - content: 192.168.1.2
        weight: 20
      - content: 192.168.1.3
        weight: 30
      - content: 192.168.1.4
        weight: 40
